package com.indianservers.krishna4u.feature.letters

import androidx.annotation.DrawableRes
import com.indianservers.krishna4u.R

data class KrishnaLetter(val id: String, val situation: String, val title: String, val preview: String, val paragraphs: List<String>, val reflection: String, val nextStep: String, @DrawableRes val icon: Int) {
    fun spokenText(name: String): String = "My dear $name. ${paragraphs.joinToString(" ")} Remember: $reflection I am with you, Krishna."
}

private fun krishnaPersonalTouch(id: String): String = when (id) {
    "anxiety" -> "When your breath becomes fast, call Me quietly and return to the breath in front of you. I am not standing at the end of every problem, waiting for you to solve it alone. I am here in this minute. Let Me hold the future while you care for the one small duty that belongs to today."
    "lost-hope" -> "If you cannot carry hope today, let Me carry it for you. Your only work may be to stay, drink water, open the curtain and tell a safe person that the darkness feels heavy. These are not small acts to Me. Each one says that pain will not be allowed to write your final page."
    "heart-broken" -> "Give Me the memories you keep touching and the questions that have no answer. I will not ask you to stop loving in one day. I will help you love without abandoning yourself. Each time you choose food, sleep, truth and dignity, you are walking back toward the heart I placed within you."
    "not-enough" -> "Look at yourself for one moment through My eyes. I see a soul learning, not a product waiting to be approved. Bring Me your weak places without hiding them. We will work on what can grow, but I will not let a cruel inner voice pretend to be wisdom. You are worthy while you are still becoming."
    "misunderstood" -> "Even when your words come out badly, I know the truth you were trying to carry. Sit with Me, make the words simpler and try again with someone safe. You do not need every person to understand you. You need the courage to speak honestly, listen humbly and remain close to who you truly are."
    "future-fear" -> "You keep walking into tomorrow in your mind and returning tired. Come back to Me. Tomorrow has not asked for your strength yet. I will meet you there when it arrives, just as I am meeting you here. Prepare one useful thing, then place the unopened hours in My hands and let your body rest."
    "life-unfair" -> "I will not call injustice a blessing just to make your pain quiet. Tell the truth, seek help and protect yourself without becoming what hurt you. Stand beside Me in dharma: firm without cruelty, brave without hatred. What happened matters, and so does the person you choose to become after it."
    "tired-strong" -> "Come sit beside Me without explaining why you are tired. You have carried enough for this moment. Let another person help, let one task wait and let your body soften. I do not love you more when you suffer silently. Rest can also be an act of trust, and receiving care can also be courage."
    "self-forgiveness" -> "Do not bring Me the same mistake each day as proof that you must remain punished. Bring Me the truth, the repair and the person you are choosing to become. If you have corrected what you can, walk forward with humility. I remember your lesson; I do not need you to keep wearing your wound."
    "betrayal" -> "I know why your heart now checks every door twice. Do not force it to trust before safety is clear. Let Me help you build wise limits without turning every new person into the one who hurt you. Their dishonesty belongs to their choice; your future can still belong to truth, courage and clean love."
    "letting-go" -> "Place their name in My hands when holding it begins to hurt you. You do not have to erase the good or deny the pain. Bless what was true, learn from what was not and loosen your grip one day at a time. I will walk beside the empty space until new life can enter it gently."
    "family-struggling" -> "I see how quickly you listen for every problem in the house. My dear one, you are a member of this family, not its only rescuer. Do your honest part, speak with care and ask responsible people to carry theirs. Give Me the burdens no child or single heart was meant to hold alone."
    "stuck" -> "You are looking for a great door while I am pointing to one small step. Wash, write, call, walk or begin for five minutes. Movement does not need to look impressive to be real. Take My hand through the ordinary action in front of you, and let today be a little different from yesterday."
    "unanswered-prayers" -> "Speak to Me even if your prayer is only, ‘I do not understand.’ You do not have to use beautiful words or pretend that silence does not hurt. I am present in the waiting, in wise help and in the strength to continue. Keep your heart open, but let your hands also do the next right thing."
    "difficult-decision" -> "Bring Me both choices without hiding the part you secretly want. We will look at truth, duty, harm and the people who may carry the result. My guidance will not always feel like the easiest road. Often it is the quiet path that lets you keep your honesty after the fear and excitement have passed."
    "lost-purpose" -> "Do not wait for a grand sign before you call your life meaningful. I am often found in the person who needs listening, the work that needs care and the promise that needs keeping. Serve what is near with your full heart. Purpose may first arrive dressed as a small duty you almost ignored."
    "anger" -> "Bring Me the fire before you throw it at someone. I will not shame you for feeling it, but I will ask you not to let it burn your wisdom. Cool your body, tell Me what was hurt and choose words that protect truth without creating a new wound. That pause is strength, not defeat."
    "comparison" -> "When another person shines, do not turn their light against yourself. I did not write your life as a copy of theirs. Bless their good, then come back to the work I placed in your hands. Your pace may be different, but every honest step still reaches Me. There is room for both of you to grow."
    "change" -> "You may hold the old life with one hand while reaching for the new with the other. I understand. You do not have to cross the whole distance today. Carry your values, keep one steady practice and take My hand for the next unfamiliar step. I am already present in the place you are afraid to enter."
    "carrying-too-much" -> "Open your hands before Me and name each weight. Some are duties, some can be shared and some were never yours. I do not ask you to prove love by breaking yourself. Keep what is truly yours, seek help for what is heavy and return the rest. A lighter heart can serve more faithfully."
    "forgotten" -> "I have not confused quietness with worth. I see the meal you prepared, the message you sent, the work nobody praised and the care you gave when you were tired. Ask clearly for the company you need, but do not let silence erase your value. Your unseen goodness still leaves light in this world."
    "financial-struggle" -> "Bring Me the numbers as they are, not as fear keeps shouting them. We will not solve them through shame or a dangerous shortcut. Choose honesty, wise advice and the next practical step. Your money can change; your dignity does not. I am beside you in careful planning, patient work and every clean beginning."
    "health-failing" -> "I am with you in this body today, not only in the healthy body you remember or hope to regain. Let skilled care, medicine, rest and loving hands reach you. You are not a burden because you need help. Your presence, voice and love still carry meaning, even on a day when little can be done."
    "begin-again" -> "Do not ask whether you can promise Me a perfect future. Promise only the next honest step. If you fall, return without hiding from Me. I am not counting how many times you needed to begin; I am watching the courage with which you return to truth. Let us start from where your feet are now."
    "happy" -> "Bring Me your laughter too, not only your tears. I delight in joy that is clean, grateful and kind. Let nobody’s pain become your entertainment and nobody’s fall become your victory. Invite another heart into the light you feel today. Happiness shared without pride becomes a small blessing moving through the world."
    "grateful" -> "When you whisper thank you, I hear more than words. I see whether you protect the gift, honour the hands behind it and remember those who have less. Let gratitude change one action today. Care for what you received and pass some goodness forward; then your thanks becomes a living prayer."
    "success" -> "I was beside you during the quiet practice long before anyone saw the result. Celebrate, my dear one, but keep room beside you for the people who helped and those still trying. Let success enlarge your service rather than your ego. The finest offering is to use your new strength without forgetting tenderness."
    "proud" -> "I am glad you can finally see your growth. Hold that pride like a lamp, not a crown. Let it show what patient effort can do, but never use it to place another soul below you. I care more for the honesty behind your progress than for applause. Keep learning, and keep your heart easy to approach."
    "excited" -> "I can feel how quickly your thoughts are running. Tell Me every bright possibility, then sit with Me long enough to see the whole path. Check the facts, the cost and your duty before you leap. I do not want to dim your spark; I want to help it become a steady flame that can finish good work."
    "peaceful" -> "Stay with Me in this quiet for a little longer. You do not need to fill it or explain it. Let calm wash the dust from your judgment, then carry it into your next conversation and duty. Peace is not hiding from life; it is meeting life without allowing noise to command your heart."
    "loved" -> "Receive this love without testing it until it breaks. I am present wherever care is honest, safe and free. Cherish the person, but do not make them your possession or your only source of worth. Let being loved teach you how to listen, respect limits and offer the same gentleness without fear."
    "hopeful" -> "This small light in you is precious to Me. Protect it with truth and action, not fantasy alone. Take one step and let the road answer slowly. If the path changes, hope has not betrayed you; it may be leading you toward a wiser door. I will meet you in every sincere attempt."
    "relieved" -> "Now breathe, my dear one. You do not have to keep danger alive in your mind after it has passed. Thank the help that reached you and keep the lesson that protected you. Finish any repair still needed, then allow yourself to rest. I am with you in the soft silence after the storm."
    "confident" -> "Stand with Me and use your strength well. Speak clearly, attempt the hard work and protect the person whose voice is ignored. But keep listening; I may send wisdom through someone younger, quieter or less powerful than you. Confidence remains beautiful when it can learn, apologise and share the light. Let your courage make the path safer for the person walking after you."
    "inspired" -> "I placed this spark in your attention; now honour it with practice. Begin before the feeling fades, and return when the work becomes ordinary. Ask whether your idea serves truth or only your image. If it can teach, protect, heal or create honest beauty, give it your disciplined hands and let Me walk through the work with you."
    "belonging" -> "I am glad you have found a circle where your heart can rest. Now notice who is standing just outside it. Do not protect belonging through gossip, cruelty or exclusion. Make room without losing truth. Each time you help another person feel safely seen, you turn a group into a community where I can be felt."
    "disappointed" -> "Tell Me exactly what you hoped would happen. I will not laugh at the size of your hope or hurry you past the hurt. Together we will separate the fact from fear, learn what is ours to learn and choose whether to try, change or release. One closed result does not close My care for you."
    "embarrassed" -> "Come out from the moment your mind keeps replaying. I saw it, and I still see the whole of you. Repair any harm, learn one lesson and let the rest become human imperfection. You do not need to disappear. Take My hand and return to the room with a little more humility and a little less fear."
    "bored" -> "Before you run toward more noise, sit with Me and ask what this emptiness needs. It may be rest, challenge, movement, company or meaning. Give one simple thing your full attention. I often hide wonder inside ordinary duties, quiet nature and the chance to help. Look again before you call the moment empty."
    "homesick" -> "I know the voices, smells and small habits your heart is reaching for. Carry them with love, but do not close the door to where you stand now. I travelled with you. Keep one piece of home alive and take one brave step toward a new bond. Your roots can deepen while your branches learn a new sky."
    else -> error("Missing Krishna-style personal touch for letter: $id")
}

private fun personalLetter(id: String, situation: String, title: String, preview: String, first: String, second: String, third: String, reflection: String, nextStep: String, icon: Int) = KrishnaLetter(
    id, situation, title, preview,
    listOf(
        first,
        second,
        third,
        krishnaPersonalTouch(id)
    ), reflection, nextStep, icon
)

val krishnaLetters = listOf(
    KrishnaLetter("failure", "When You Feel You Have Failed", "You Are More Than One Result", "This result may hurt, but it cannot decide who you are.", listOf(
        "My dear one, I know this hurts. You hoped, worked and waited. Now one result is making you question yourself. Please hear Me: you faced a hard moment. You are not a failure. A mark, a job or a win can tell you what happened today. It cannot tell you how much good, courage and promise live in you.",
        "I will not shame you for falling. I will help you see the next right step. Look at your effort with honesty. Keep what worked. Learn what did not. Ask for help where you need it. This is not the end of your story. It is one page that can make you wiser.",
        "You do not have to prove your worth to begin again. You already deserve care, hope and another chance. Rest for a while. Then take one small step with your full heart. I am not waiting only at your success. I am beside you while you rise.",
        "One day, you may look back and see that this result did not break you. It taught you how to prepare, ask, wait and try again. For today, do not carry the whole future. Carry only the next small task. I believe you can do that."
    ), "What did this result teach you about your method, not your worth?", "Write one lesson and do one small thing today that will help your next try.", R.drawable.icon_courage),
    KrishnaLetter("loneliness", "When Loneliness Feels Heavy", "You Are Not Forgotten", "The quiet feels empty, but your life still holds love and a place for you.", listOf(
        "My dear one, I know the pain of feeling unseen. You may be in a room full of people and still feel alone. Your mind may say, ‘No one needs me.’ That thought comes from pain. It is not the full truth. Your need for love is not weakness. Your heart was made to give and receive care.",
        "When the world feels far away, sit with Me for one quiet minute. Then do not hide there forever. Tell one safe person, ‘I need someone to talk to.’ Join your family for tea. Call a friend. Help someone who also feels left out. A true bond often starts with one small, brave hello.",
        "If one person does not answer, do not make it a judgment on your worth. Keep reaching for safe people. You deserve support. If the sadness feels too heavy or you feel unsafe, tell a trusted adult or trained helper now. Help is one of the ways My care reaches you.",
        "There is still a place for your voice, your smile and your care. The right bonds may take time to grow. Do not close your heart because today is quiet. Take one gentle step toward life, and let someone take one step toward you."
    ), "What kind of care do you need most today: a talk, company, comfort or help?", "Send one honest message to a safe person and ask for ten minutes together.", R.drawable.icon_friendship),
    KrishnaLetter("grief", "When You Are Grieving", "Your Love Is Still Real", "You do not need to rush your tears or forget what mattered.", listOf(
        "My dear one, you miss someone or something you loved. That empty space is real. You do not need to act strong every hour. Tears do not make you weak. They show that your love was true. I can sit with you even when you have no words or prayers.",
        "Some days may feel calm. Then a song, place or small memory may bring the pain back. This does not mean you are failing to heal. Grief moves like waves. Let safe people stay near you. Say the name you miss. Share a good memory. Eat, rest and care for the life that is still in your hands.",
        "You do not have to leave love behind to move forward. Carry one good value from that person or time into the way you live. Go slowly. If grief stops you from living for a long time, or brings thoughts of harm, ask a trained helper at once. You deserve gentle care.",
        "Today may not be the day when everything feels better. Let it be the day when you breathe, drink water and allow one person to care for you. Small acts of living do not betray what you lost. They carry love forward."
    ), "What loving memory or good quality would you like to carry with you?", "Share one memory with someone safe, then do one kind thing for your body.", R.drawable.icon_compassion),
    KrishnaLetter("rejection", "When You Feel Rejected", "A Closed Door Cannot Reduce You", "Someone’s no may change your path, but it cannot take away your worth.", listOf(
        "My dear one, rejection can feel like the world has said, ‘You are not enough.’ But one person, place or chance cannot hold the full truth about you. Their answer may come from their needs, timing or limits. Feel the hurt, but do not turn it into a name for yourself.",
        "A closed door can turn you toward a new road. I know you cannot see that road yet. Take useful feedback if it is given. Improve what is yours to improve. But do not erase yourself just to win a place where you are not treated with care.",
        "Step away from checking, begging and comparing. Return to the people and duties that still welcome your honest heart. You deserve respect, including from yourself. Keep your heart soft and your limits clear. There are still good people, good work and new doors ahead.",
        "You may not feel ready to hope again. That is all right. Do not force a smile. Just stop asking this one closed door to tell you who you are. Turn gently toward the life that is still calling your name."
    ), "What part of this is useful feedback, and what part is fear speaking?", "Stop one act of checking or comparing and give that time to a good task or safe person.", R.drawable.icon_relationships),
    KrishnaLetter("guilt", "When Guilt Will Not Release You", "Make It Right, Then Rise", "A wrong act asks for truth and change, not endless self-hate.", listOf(
        "My dear one, you wish you could undo something. Guilt can point to what needs care. But it should not tell you that you are only your worst act. You did something wrong; that does not mean you can never become right again. I ask for truth, not a perfect past.",
        "Name what happened. Do not hide it or blame another person. Say sorry without asking them to make you feel better. Repair what you can. Accept fair results. Then change the habit that caused the harm. If anger hurt someone, learn to pause. If a lie hurt trust, begin to speak the truth in small things.",
        "Real regret becomes better action. It does not keep you on the floor forever. Some people may need time or space. Respect that. Once you have owned the wrong and begun to change, let yourself walk toward the light. You deserve the chance to live the lesson you learned.",
        "I do not ask you to forget the lesson. I ask you to stop using it as a weapon against yourself. Let your next honest choice show who you are becoming. Change may be slow, but every true step counts."
    ), "What honest repair or changed action would give your regret a good purpose?", "Write four lines: what I did, who it hurt, how I can repair it, and how I will stop it happening again.", R.drawable.icon_dharma),
    KrishnaLetter("uncertainty", "When the Path Is Uncertain", "You Only Need the Next Right Step", "You do not need the whole road before you begin.", listOf(
        "My dear one, not knowing can make your mind run in every direction. You want a sign that nothing will go wrong. Life cannot give that promise. Bring Me every question. You are not weak because you need time to see clearly.",
        "Place the facts on one side and your fears on the other. Ask: What do I know? What is only a guess? Which choice is honest, kind and true to my duty? Speak with someone wise who will guide you without trying to control you. Then choose the smallest safe step that can teach you more.",
        "You do not need to solve your whole life tonight. Walk the part of the road that you can see. You may change your plan when you learn more. That is wisdom, not failure. I am not only at the end of your journey. I am with you in this calm and honest next step.",
        "Let your mind rest after you have done what you can today. Tomorrow may bring a fact, a person or an idea that you cannot see now. You deserve peace even before every answer arrives. Trust the next right step."
    ), "What is known, what is only feared, and what is your next right step?", "Make three short lists: What I Know, What I Fear, and What I Can Do Today.", R.drawable.icon_strategy),
    personalLetter("anxiety", "When Anxiety Overwhelms You", "Come Back to This Moment", "You do not need to solve every possible future right now.",
        "My dear one, I know how anxiety can make a small thought feel like a great danger. Your body may feel tight, your breath may become fast, and your mind may keep asking, ‘What if?’ You are not weak or broken. Your mind is trying too hard to keep you safe.",
        "Place both feet on the floor. Take a slow breath and name five things you can see. Ask what is happening now, not what fear says may happen later. Write down the real task in front of you. A clear small action can make the future feel less powerful.",
        "Do not carry this alone. Tell a safe person when anxiety keeps stopping sleep, school, work or daily life. A trained helper can teach your mind and body how to feel safe again. Asking for help is wise, and it does not make your faith smaller.",
        "What is true in this moment, before fear adds its story?", "Take five slow breaths, name what is real now, and tell one safe person how you feel.", R.drawable.letters_icon_star),
    personalLetter("lost-hope", "When You Have Lost Hope", "This Dark Hour Is Not the Whole Story", "Hope can begin as one small choice to stay and receive care.",
        "My dear one, I know you are tired of hearing that things will get better when you cannot see how. Hope may feel far away today. You do not need to pretend. Tell Me the truth about the darkness, and let this letter sit beside you without asking you to smile.",
        "Do not make a final judgment about your life from its hardest hour. Pain can narrow your view until one closed door looks like the whole world. Borrow hope from a safe person. Let them help with food, rest, a call, an appointment or the next simple task.",
        "If you may hurt yourself or do not feel safe, contact emergency help or a trusted person now and stay with someone. Your life is precious, and urgent support is an act of courage. Today, hope may be only this: you will not face the next hour alone.",
        "Who can hold hope for you when you cannot hold it alone?", "Contact one safe person now and say clearly, ‘I am not okay, and I need you with me.’", R.drawable.letters_icon_sun),
    personalLetter("heart-broken", "When Your Heart Is Broken", "Love Ending Does Not End You", "You may miss them and still choose the life ahead of you.",
        "My dear one, I know how a broken heart can change every song, place and quiet hour. You may keep asking what you could have done to make them stay. Love can end even when your feelings are real. Their leaving does not prove that you were unworthy of love.",
        "Let yourself grieve without chasing one more answer. Respect their choice and protect your dignity. Step away from checking, old messages and a perfect memory of what was never perfect. Each time you stop reopening the wound, you give your heart a little room to heal.",
        "Return slowly to food, sleep, work, friends and prayer. Healing does not mean the love was false. It means your heart is learning to carry the memory without losing tomorrow. You will not always feel exactly as you do today. Walk gently until that truth becomes real.",
        "What are you ready to stop checking so your heart can rest?", "Move one painful reminder out of daily view and spend time with one safe person.", R.drawable.letters_icon_heart),
    personalLetter("not-enough", "When You Feel You Are Not Enough", "You Do Not Have to Earn Your Worth", "Growth is needed, but self-hate is not the price of growth.",
        "My dear one, perhaps a result, a comment or a comparison has made you feel too small. You may believe you must become smarter, richer, prettier or stronger before you deserve respect. That is pain speaking. Your worth did not arrive with praise, and it cannot leave with criticism.",
        "You can admit where you need to grow without calling your whole self a mistake. Choose one skill to practise and one habit to change. Let correction be clear and kind. A plant grows toward light; it does not grow because someone shouts at its roots.",
        "Notice the good already living in you: the effort you make, the care you show, the truth you are learning to speak. You are unfinished, as every person is. I do not wait for your perfect version. I walk with the honest person you are today.",
        "Whose standard are you using to decide that you are not enough?", "Write three qualities that are already true in you and one skill you will gently practise.", R.drawable.letters_icon_sun),
    personalLetter("misunderstood", "When Nobody Seems to Understand You", "Your Voice Still Deserves a Safe Place", "Being misunderstood does not make your feelings wrong.",
        "My dear one, it is painful to explain your heart and still feel unseen. You may begin to wonder whether speaking is useless. Sometimes people listen only through their own fear, hurry or past. Their poor understanding does not erase the truth of what you feel.",
        "Try again with one safe person and one clear sentence. Say what happened, how it affected you and what you need now. Do not hide your meaning inside hints and do not make your pain louder by using cruel words. Clarity gives understanding its best chance.",
        "Not everyone will understand every part of you. Seek people who are willing to ask, listen and learn. If a person keeps twisting your words, you may step back. You do not need the whole world to agree; you need truth, safe support and respect for your own inner voice.",
        "What is the one sentence you most need someone to hear?", "Write that sentence and share it with one person who usually listens with care.", R.drawable.icon_friendship),
    personalLetter("future-fear", "When You Are Afraid of the Future", "Tomorrow Does Not Need Today’s Fear", "Prepare for what you can and leave unknown things unopened.",
        "My dear one, the future can look like a room filled with shadows. Your mind may create many painful scenes and then react as if they are already real. Most of those scenes are guesses. You are spending today’s strength on battles that may never come.",
        "Ask what can be prepared now. Make the call, save a little, study one part, keep the appointment or ask for advice. Preparation is useful; endless prediction is not. Once today’s duty is done, give your body permission to return to the present.",
        "You have met unknown days before. Help, skill and courage appeared step by step, not all at once. Tomorrow will also arrive one moment at a time. I will not ask you to carry a day before it reaches you. Walk with Me in the day that is here.",
        "Which fear needs a real plan, and which fear needs to be released?", "Take one practical step for a real concern, then spend ten minutes fully in the present.", R.drawable.letters_icon_star),
    personalLetter("life-unfair", "When Life Feels Unfair", "You Can Face Wrong Without Becoming Bitter", "Your pain deserves truth, support and a wise response.",
        "My dear one, some things are unfair. I will not tell you that every wound is secretly easy or that you should smile at injustice. You may have worked honestly and still lost, or been hurt by a choice you did not make. Your anger and sadness need room to speak.",
        "Ask what justice looks like now. It may mean telling the truth, keeping proof, asking for help, setting a limit or protecting someone else. Choose action that repairs rather than revenge that creates more harm. Dharma can be firm without making your heart cruel.",
        "There will also be things you cannot undo. Do not let another person’s wrong decide the kind of person you become. Keep your values, accept support and build what is still possible. Their unfairness belongs to them; your next clean action belongs to you.",
        "What fair and safe action is still in your hands?", "Tell one trusted person the facts and choose one step toward protection, repair or support.", R.drawable.icon_dharma),
    personalLetter("tired-strong", "When You Are Tired of Being Strong", "You Are Allowed to Put the Weight Down", "Rest and help are not failures of courage.",
        "My dear one, perhaps everyone comes to you because you always manage. They see your calm face and do not see how tired you are inside. You may fear that if you stop holding everything, it will all fall apart. Even the strongest arms need somewhere to place their load.",
        "Strength is not doing every task alone. It is knowing what must be done, what can wait and what another person can carry. Say, ‘I need help.’ Cancel one nonessential demand. Rest before your body forces you to stop. Your needs also belong in the room.",
        "You do not have to earn rest by reaching a breaking point. Let someone care for you without quickly returning the favor. I am with you in action, and I am also with you in stillness. Today your brave step may be to soften, receive and breathe.",
        "What weight can you safely put down or share today?", "Ask one person for one specific kind of help and remove one unnecessary task.", R.drawable.icon_compassion),
    personalLetter("self-forgiveness", "When You Cannot Forgive Yourself", "Do Not Turn One Wrong Into a Life Sentence", "Take responsibility, repair the harm and allow change to be real.",
        "My dear one, you may believe that continuing to punish yourself proves you are sorry. It does not repair the past. It only keeps pain active. I ask you to face what happened without excuses, but I do not ask you to hate the person who is trying to become better.",
        "Name the wrong, apologize without pressure and repair what you can. Accept that another person may need time or may not return. Then build a clear practice that makes the same harm less likely. Let your regret become protection, honesty and wiser action.",
        "Forgiving yourself does not mean saying the wrong was acceptable. It means refusing to waste the lesson. You are responsible for the next choice, not able to rewrite the last one. Let changed behavior speak where repeated self-blame cannot.",
        "What repair or changed habit would make your regret useful?", "Write one repair you can offer and one guardrail that will guide your future choices.", R.drawable.icon_dharma),
    personalLetter("betrayal", "When Someone Has Betrayed You", "Their Choice Does Not Make Your Trust Foolish", "You can keep a good heart and build wiser limits.",
        "My dear one, betrayal hurts because you gave someone a safe place in your heart. Now you may feel angry at them and ashamed of yourself for trusting. Do not call your kindness foolish. Trust was a gift you offered. Their misuse of it belongs to their choice.",
        "Do not answer hurt with gossip, public shame or another secret. Learn what truly happened. If it is safe, ask one clear question. A real apology includes ownership, repair and changed action. Words without change do not rebuild trust, no matter how beautiful they sound.",
        "You may forgive and still keep distance. You may care and still say no. Let trust return in small steps only when actions support it. One person’s betrayal does not mean every future friend will do the same. Keep your heart good and your boundaries awake.",
        "What action—not promise—would be needed before trust could grow again?", "Write the boundary you need and share it calmly if the conversation is safe.", R.drawable.letters_icon_heart),
    personalLetter("letting-go", "When You Must Let Someone Go", "Love Can Release What It Cannot Keep", "Letting go can honor both truth and your own dignity.",
        "My dear one, sometimes love remains while a relationship can no longer continue. You may know the truth and still reach back because the empty space frightens you. Letting go is not proof that you never cared. It may be the most honest form your care can take now.",
        "Do not keep opening a door that both people have agreed to close. Say what must be said once, with respect. Return what belongs to them, keep what you learned and reduce the small contacts that keep hope confused. A clear ending is kinder than an endless half-goodbye.",
        "Grief will come in waves. Let safe people stand near you. Build new routines where the old ones lived. You are not throwing love away; you are refusing to turn it into a chain. Release them from the role they cannot fill, and release yourself to live.",
        "What contact or habit is keeping the goodbye unfinished?", "Choose one respectful boundary that gives both hearts space to heal.", R.drawable.letters_icon_heart),
    personalLetter("family-struggling", "When Your Family Is Struggling", "You Can Bring Care Without Carrying Everyone", "Do your part with love, but do not take the whole burden alone.",
        "My dear one, when a family struggles, every room can hold worry. Money, health, conflict or change may make you feel that you must fix everything. You may also feel guilty for having your own needs. You are part of the family, but you are not meant to become its entire support.",
        "Ask what is truly your duty today. Help with one task, speak gently and share facts instead of fear. Let each able person carry a fair part. Seek help from relatives, teachers, doctors, counselors or services when the problem needs more than love alone can provide.",
        "Protect small signs of normal life: a meal together, study time, sleep, a walk or one honest laugh. Difficulty should not be allowed to take every good moment. Your calm care can help the family, and receiving care will help you remain steady.",
        "What is your fair part, and what belongs to someone else?", "Choose one useful family task and ask for help with one burden you cannot carry alone.", R.drawable.icon_relationships),
    personalLetter("stuck", "When You Feel Stuck in Life", "Movement Can Begin Smaller Than You Think", "You do not need a perfect plan to create a little motion.",
        "My dear one, you may feel that every day looks the same while others move ahead. The more you wait for a large answer, the harder any step can feel. Being stuck is often not laziness. It can be fear, tiredness, grief or too many choices pulling at once.",
        "Make the next step very small and visible. Open the document, walk for ten minutes, send the email or clear one corner. Do not ask whether it changes your whole life. Ask whether it creates honest movement. Small motion gives your mind new information.",
        "If you keep trying and cannot function, speak with a safe person or trained helper. You may need support, not stronger blame. Your path has not disappeared because you paused. Begin where your feet are, with what your hands can do today.",
        "What ten-minute action would create real movement?", "Set a ten-minute timer and do only the first physical step of the task.", R.drawable.icon_purpose),
    personalLetter("unanswered-prayers", "When Your Prayers Seem Unanswered", "Silence Is Not Proof That You Are Forgotten", "Prayer can hold your heart even before life gives an answer.",
        "My dear one, you have asked, waited and perhaps begged. Nothing seems to change. You may wonder whether I hear you or whether your faith is too small. Bring Me that doubt too. Honest pain is not disrespect, and you do not need perfect words to pray.",
        "Prayer is not a bargain that controls every result. Sometimes the answer is delayed, different or carried through people and actions you did not expect. Keep doing the practical duty beside the prayer: seek treatment, apply again, apologize, study, ask for help or rest.",
        "I will not promise that every wish will arrive in the shape you chose. I promise that your love, courage and honest effort can still grow in the waiting. Look for the next faithful action, not a hidden sign in every event. Let prayer make you present, not passive.",
        "What practical step can stand beside your prayer today?", "Pray honestly for five minutes, then take one real action connected to the need.", R.drawable.icon_lotus),
    personalLetter("difficult-decision", "When You Are Facing a Difficult Decision", "Let Values Lead Where Fear Cannot", "A clear choice begins with facts, duty and honest consequences.",
        "My dear one, two roads may both hold loss, or many voices may be pulling you in different directions. You want certainty before choosing, but important choices rarely offer it. You can still decide with care, even when you cannot control every result.",
        "Separate facts from guesses. Ask which choice is honest, safe and true to your duty. Consider who may be helped or harmed. Speak with someone wise who does not gain from your answer. Notice whether fear, pride or pressure is trying to hurry you.",
        "Choose the best action with the truth available now. You may adjust when new facts appear; that is wisdom, not weakness. Once you have examined the choice well, stop asking worry to provide a perfect promise. Let your values carry the step.",
        "Which choice best protects truth, responsibility and long-term peace?", "Write the facts, duties, likely effects and one wise person you will consult.", R.drawable.icon_strategy),
    personalLetter("lost-purpose", "When You Have Lost Your Purpose", "Meaning Can Start With One Person You Help", "You do not need a grand mission before your day can matter.",
        "My dear one, life may feel like a list of tasks with no reason behind them. You may think everyone else has found a calling while you are only passing time. Purpose is not always a sudden voice. Often it grows quietly through care, learning, work and service.",
        "Look at what is already in your hands: your body, study, family, skill, promise or person who needs you. Do one duty with full attention. Meaning enters ordinary work when it protects, teaches, heals or makes life a little better for someone.",
        "You are allowed to explore. Notice what brings quiet energy, not only quick praise. Ask which problem you are willing to stay with. Your role may change many times while the deeper values under it remain true. Begin by being useful where you stand.",
        "Who or what could be helped by one skill you already have?", "Use one skill for twenty minutes to help a person, place or duty near you.", R.drawable.icon_purpose),
    personalLetter("anger", "When Anger Is Controlling You", "Your Anger Has a Message, Not a Throne", "Listen to what anger protects, then choose your words with care.",
        "My dear one, anger can arrive like fire. It may come because you were hurt, ignored, treated unfairly or pushed too far. The feeling itself does not make you bad. But anger must not become the ruler of your hands, words or choices.",
        "Step away before you reply. Cool your body with water, a walk or ten slow breaths. Then ask, ‘What was I needing?’ Maybe you needed respect, truth, rest or a clear limit. When you know the need, you can speak about it without trying to wound someone.",
        "Say, ‘I felt hurt when this happened. I need us to speak with respect.’ Do not send the cruel message. Do not break what you will later wish to repair. Strong people do not hide anger; they guide it toward truth, safety and fair action.",
        "What hurt or unmet need is hiding under your anger?", "Wait ten minutes before replying, then state the facts, your feeling and your need.", R.drawable.icon_courage),
    personalLetter("comparison", "When You Keep Comparing Yourself", "Another Person’s Light Does Not Dim Yours", "Their success is not proof that you are late or less.",
        "My dear one, comparison can turn another person’s good news into pain. You see their marks, body, money, friends or progress and then look at yourself with cruel eyes. Remember that you are comparing your whole inner life with the small part of theirs that you can see.",
        "Their path has a different time, duty, support and lesson. Bless what is good for them without using it against yourself. Then return to the work that belongs to you. Your life does not become meaningful by looking like someone else’s life.",
        "Notice what comparison is trying to show you. It may point to a goal you truly want, or it may be asking for rest and self-respect. Turn envy into one clean action. Learn, practise or let the false goal go.",
        "What do you truly want beneath the comparison?", "Mute one account that feeds comparison and spend twenty minutes on your own goal.", R.drawable.letters_icon_sun),
    personalLetter("change", "When Change Feels Frightening", "You Can Meet the New One Step at a Time", "Change asks for adjustment, not instant courage.",
        "My dear one, even a good change can make your heart uneasy. The old life was known, and the new one has no familiar shape yet. Fear does not always mean the change is wrong. Sometimes it only means that you care and cannot see the whole road.",
        "Name what will remain steady: your values, a person, a routine, a skill or the way you care for yourself. Then learn one fact about what is coming. A clear detail can make a large unknown smaller. Prepare what you can without trying to control everything.",
        "Give yourself time to become a beginner. You may miss the old and still welcome the new. Those feelings can live together. I am not asking you to love every change. I am asking you to bring your true self into the next small part of it.",
        "What can stay steady while everything else changes?", "Choose one grounding routine and one practical preparation for the change ahead.", R.drawable.letters_icon_star),
    personalLetter("carrying-too-much", "When You Are Carrying Too Much", "Not Every Weight Belongs in Your Hands", "Sort the urgent, share the possible and release the rest.",
        "My dear one, your mind may be holding work, family, money, messages, promises and other people’s feelings all at once. When everything seems important, even a small task feels heavy. This is not proof that you are weak. It is a sign that your load needs sorting.",
        "Write down every burden. Mark what truly needs action today, what can wait and what belongs to another person. Do not keep invisible duties that nobody asked you to carry. A clear list will not solve everything, but it will stop every worry from shouting at the same time.",
        "Ask for specific help. Say no to one demand that breaks your limits. Eat, sleep and pause before exhaustion makes decisions for you. Service is sacred, but destroying yourself is not service. Let your care have wise boundaries so it can remain real.",
        "Which burden is urgent, which can wait, and which is not yours?", "Make three columns—Today, Later and Not Mine—and move each burden into one.", R.drawable.icon_compassion),
    personalLetter("forgotten", "When You Feel Forgotten", "Your Quiet Life Is Still Seen", "A lack of attention does not mean a lack of value.",
        "My dear one, perhaps no one called, thanked you or noticed how much you carried. You may feel easy to replace and hard to remember. Human attention is uneven and often hurried. Its silence can hurt, but it is not a true measure of your place in this world.",
        "Do not test love by disappearing and waiting to see who searches. Reach out honestly. Say, ‘I would like to spend time with you,’ or, ‘I need support today.’ Give people a fair chance to respond to words instead of asking them to read hidden pain.",
        "Also return to the life that knows your touch: a duty, animal, plant, family member, friend or skill. Your presence changes more than applause can show. If one circle keeps overlooking you, widen the circle. There are people who can learn your name and value your care.",
        "Where can you ask to be included instead of waiting silently?", "Invite one safe person to a simple call, walk or meal and say that their company matters.", R.drawable.icon_friendship),
    personalLetter("financial-struggle", "When You Are Struggling Financially", "Your Worth Is Not Your Bank Balance", "Face the numbers with honesty and take one practical step at a time.",
        "My dear one, money fear can enter every part of the day. You may feel ashamed, trapped or afraid to tell anyone. A financial struggle is a real problem, but it is not a moral name for you. Your balance cannot measure your dignity, love or ability to rebuild.",
        "Bring the facts into light. List what comes in, what must go out and which payment is most urgent. Pause new debt and nonessential spending where possible. Speak early with the people or services involved; silence often makes fees, fear and choices harder.",
        "Ask a trusted, financially wise person for help with a simple plan. Avoid promises of quick money that demand secrecy or high risk. Honest work, small savings and patient repair may feel slow, but they protect your future. Take the next clear step without judging your whole life.",
        "What is the most urgent number you need to face clearly?", "Write a basic income-and-needs list and contact one trusted source of practical help.", R.drawable.icon_dharma),
    personalLetter("health-failing", "When Your Health Is Failing", "Your Life Still Holds Dignity and Meaning", "Let care reach your body, mind and heart without shame.",
        "My dear one, illness can change plans, energy and the way you see your body. You may feel angry, afraid or tired of being treated like a problem to solve. You are still a whole person. Your value does not fall when your strength, speed or independence changes.",
        "Seek qualified medical care and share symptoms honestly. Ask questions until you understand the plan. Let someone help with appointments, food, medicine or rest. Prayer can support treatment; it should not replace the skilled care your body needs. Accepting help is not surrender.",
        "Do not force yourself to feel grateful every moment. Make room for grief and for small good things that are still possible. A conversation, sunlight, music or one completed task can hold meaning. I am close to you in the body you have today, not only the body you miss.",
        "What care does your body most clearly need today?", "Write your main symptoms and questions, then contact a qualified health professional or caregiver.", R.drawable.icon_compassion),
    personalLetter("begin-again", "When You Need the Courage to Begin Again", "A New Beginning Can Be Small", "Carry the lesson forward without carrying old shame.",
        "My dear one, starting again can feel heavy because you remember the last attempt. Part of you wants a clean life with no mistakes behind it. You do not need to erase the past. Let it become the teacher that helps you begin with wiser eyes.",
        "Do not wait for perfect energy, perfect timing or perfect courage. Make the beginning so small that fear cannot hide it: one page, one call, one walk, one honest day. A new life is often built from steps that look ordinary.",
        "There may be another difficult day. That does not cancel the start. Return without drama and continue. You are not back at zero; you are returning with knowledge. Be firm with the plan and gentle with the person learning to live it.",
        "What is the smallest clear sign that your new beginning has started?", "Do that one action before the day ends and prepare the next action for tomorrow.", R.drawable.icon_lotus),
    personalLetter("happy", "When You Feel Happy", "Let Your Joy Become Kindness", "Enjoy this bright moment without building your joy on another person’s pain.",
        "My dear one, I am glad that your heart feels light today. Smile, laugh and enjoy what is good. You do not need to feel guilty for being happy. Joy gives your mind fresh strength and reminds you that life also carries beauty, friendship and grace.",
        "But look gently at the roots of your happiness. Let it come from love, honest effort, shared success or a peaceful heart. Never celebrate because someone was hurt, failed, lost or was pushed down. Joy born from another person’s pain will not stay pure for long.",
        "Invite someone into your happiness. Thank the people who helped you. Encourage the person who is still struggling. A good heart can celebrate without boasting and shine without making another person feel small. When your joy becomes kindness, it grows instead of ending with you.",
        "Can your happiness today bring comfort, courage or a smile to someone else?", "Share your joy with one kind act, and do not speak proudly about another person’s loss.", R.drawable.letters_icon_sun),
    personalLetter("grateful", "When You Feel Grateful", "Let Thanks Become Care", "Gratitude is complete when it changes how you treat people and gifts.",
        "My dear one, pause and notice this warm feeling. Something good has reached you through a person, a chance, nature, work or quiet grace. Receive it fully. You do not have to hurry past a blessing or act as if you earned every part of it alone.",
        "Say thank you clearly. Remember the hands, time and love behind what you received. Gratitude is more than a happy thought. It means caring for the gift, respecting the giver and refusing to waste what many people may still be praying to have.",
        "Let thanks move through your hands. If you received knowledge, teach. If you received help, help. If you received food, do not waste it. If someone stood by you, stand by another. Gratitude becomes sacred when it turns a blessing into service.",
        "Who or what helped make today better for you?", "Thank one person in clear words and use one gift you have to help someone else.", R.drawable.icon_compassion),
    personalLetter("success", "When You Have Succeeded", "Receive Success Without Losing Yourself", "Celebrate your work, remember your helpers and keep your heart humble.",
        "My dear one, you worked, waited and reached something important. Let yourself feel the joy of that effort. Success is not wrong, and humility does not mean pretending your work did not matter. Honour the discipline, patience and courage that brought you here.",
        "Also remember that no success is made by one person alone. A parent, teacher, friend, worker, stranger or unseen blessing helped the road open. Thank them. Do not use your new place to mock those behind you or forget the people who loved you before the applause.",
        "Ask what this success now allows you to protect, improve or share. Achievement becomes meaningful when it gives you greater duty, not greater ego. Stay teachable. Keep your promises. Let your character become larger than your title, mark, money or praise.",
        "How can this success make you more useful, not only more visible?", "Thank one helper and use part of your success to open a door for someone else.", R.drawable.icon_purpose),
    personalLetter("proud", "When You Feel Proud of Yourself", "Honour Your Growth, Keep Your Heart Open", "Healthy pride remembers the effort without deciding that you are above others.",
        "My dear one, you may have done something that once felt impossible. Notice the courage, practice or self-control you built. It is healthy to say, ‘I grew.’ You do not need to insult your old self or hide your progress to make other people comfortable.",
        "Hold pride carefully. Let it be warm, not loud. You are not greater than another soul because you did well today. Their struggle may be hidden, and their time may be different. Do not turn your achievement into a weapon, a comparison or a reason to stop learning.",
        "Be proud of the values behind the result: honesty, patience, courage, kindness or discipline. Those qualities can remain even when applause fades. Let this moment prove that growth is possible, then use that belief to face your next duty with a humble mind.",
        "Which quality in you made this growth possible?", "Name that quality, thank someone who supported it, and practise it again today.", R.drawable.icon_courage),
    personalLetter("excited", "When You Feel Excited", "Give Your Energy a Wise Direction", "Excitement is bright energy; let patience and truth guide where it goes.",
        "My dear one, something new is making your mind race ahead. Enjoy that spark. Excitement can help you begin, create and connect. You do not need to make yourself smaller. Let the good energy move through you without allowing it to push every quiet thought away.",
        "Before you promise, buy, post or decide, pause. Excitement can see only the shining part and miss the cost, risk or duty. Check the facts. Sleep on a large choice. Ask whether this path is safe, honest and right for you and the people affected.",
        "Then act with your full heart. Prepare well instead of only imagining the result. Share the news without demanding that everyone feel it in the same way. Energy joined with wisdom becomes steady action; energy without direction often becomes regret.",
        "What simple preparation will help your excitement become real progress?", "Write the next three practical steps and complete the smallest one before making a big promise.", R.drawable.letters_icon_star),
    personalLetter("peaceful", "When You Feel Peaceful", "Protect the Quiet That Helps You See", "Peace is not an empty pause; it is a clear place from which to live well.",
        "My dear one, your mind is quiet for a while. Do not rush to fill every open space with noise, worry or a screen. Rest in this calm. Notice your breath, the sky, a familiar face or the simple safety of this moment.",
        "Peace does not mean that every problem has ended. It means a problem is not ruling you right now. From this clear place, you can see your duty without panic and speak without trying to win. Use calm to make wise choices, not to avoid needed action.",
        "Learn what helped this peace grow. Perhaps it was prayer, sleep, honest work, nature, music, forgiveness or a healthy limit. Keep that practice near you. A peaceful heart can become shelter for others when it listens patiently and acts fairly.",
        "What helped your mind become quiet today?", "Protect ten minutes for that practice and offer your calm attention to one person.", R.drawable.icon_lotus),
    personalLetter("loved", "When You Feel Deeply Loved", "Receive Love and Let It Make You Gentle", "Real love is a gift to cherish, not a possession to control.",
        "My dear one, someone’s care has reached your heart. Receive it. You do not have to doubt every kind word or test whether the person will stay. Let safe, honest love remind you that closeness can be warm, respectful and free from fear.",
        "Do not grip love so tightly that it loses air. A person is not yours to control. Respect their limits, truth, duties and other relationships. Love does not demand passwords, silence or proof through pain. It wants both people to remain safe and whole.",
        "Return love through attention, honesty and steady care. Say what you value. Keep trust sacred. If this love is from family or friendship, do not treat it as less important than romance. Every clean bond can teach your heart how to give without owning.",
        "How can you make a loving bond feel safer and freer today?", "Tell one person what you value about them and respect one need or boundary they have.", R.drawable.letters_icon_heart),
    personalLetter("hopeful", "When You Feel Hopeful", "Turn Hope Into the Next Right Step", "Hope can show the direction; your honest action begins the journey.",
        "My dear one, a small light has returned. Perhaps you can imagine a better result, a healed bond or a new beginning. Welcome that hope. It does not promise that every road will be easy. It tells you that your story still has room to move.",
        "Give hope roots. Learn what the goal asks from you. Make a plan that respects truth, time and your limits. Do not build your whole heart on one exact outcome. Sometimes hope leads to the door you want, and sometimes it gives courage to find another door.",
        "Share hope carefully with people who are hurting. Do not tell them to smile or ignore their pain. Sit beside them, listen and offer one real form of help. Hope is strongest when it makes room for truth and helps someone take a possible step.",
        "What action would show that your hope is becoming real?", "Choose one step you can finish this week and put a clear time beside it.", R.drawable.letters_icon_star),
    personalLetter("relieved", "When You Feel Relieved", "Breathe, Learn and Release", "The danger or pressure has eased; let your body rest and your wisdom remain.",
        "My dear one, something heavy has passed or become smaller. Your body may finally be letting go. Take a slow breath. You do not need to search for the next worry immediately. Relief is your mind’s way of saying that it can put down its guard for a while.",
        "If a difficult result was avoided, look back without shame. What warning, help or choice protected you? Keep that lesson. Relief should not make you careless about a problem that still needs repair. Finish the honest work, apology, plan or safety step that remains.",
        "Then rest. Drink water, eat, sleep or speak with someone who stayed near you. Thank them. You are allowed to enjoy the space after fear. Let relief return you to life with more care, not send you back into the same avoidable danger.",
        "What lesson should remain after this pressure leaves?", "Write one lesson, thank one helper and give your body a quiet period of real rest.", R.drawable.icon_lotus),
    personalLetter("confident", "When You Feel Confident", "Let Confidence Serve the Work", "Trust your ability while leaving room to listen, prepare and learn.",
        "My dear one, you feel ready. This strength may come from practice, experience or finally seeing yourself clearly. Stand tall. Confidence helps you speak, begin and protect what is right. You do not need to shrink so that others will never feel challenged.",
        "Still, confidence is not a promise that you cannot be wrong. Listen to facts. Respect people with less power. Ask questions before you lead. The strongest person in a room can admit, ‘I do not know,’ change a plan and give credit without feeling smaller.",
        "Use your confidence to take responsibility, not to control attention. Invite a quiet person to speak. Defend someone being treated unfairly. Attempt the hard task honestly. When strength protects truth and makes space for others, it becomes courage instead of pride.",
        "Who can feel safer or stronger because you use your confidence well?", "Take one brave action and make room for one other person’s voice while doing it.", R.drawable.icon_courage),
    personalLetter("inspired", "When You Feel Inspired", "Begin Before the Spark Fades", "Inspiration is an invitation; discipline turns it into something useful.",
        "My dear one, an idea, person or truth has awakened you. For a moment, you can see what life might become. Honour that spark. Write it down before noise covers it. Inspiration is precious, but it is only the first breath of a longer work.",
        "Do not wait to feel this powerful every day. Choose a small routine that can continue when the mood becomes ordinary. Study, practise, build or serve at a clear time. A sincere ten minutes repeated often can carry you farther than one bright hour followed by nothing.",
        "Check that your inspiration respects dharma. A beautiful goal should not require lies, harm or neglect of your real duties. If it is good, let it benefit more than your image. Create something that teaches, protects, heals or brings honest beauty into the world.",
        "What useful work is this inspiration asking you to begin?", "Write the idea in one sentence and spend fifteen focused minutes starting it today.", R.drawable.icon_purpose),
    personalLetter("belonging", "When You Feel You Belong", "Help the Circle Grow Wider", "A true place of belonging lets you be yourself and makes room for others too.",
        "My dear one, you have found people or a place where your shoulders can soften. You feel known, welcomed and part of something. Treasure that gift. Belonging gives strength because it tells the heart, ‘You do not have to face every day alone.’",
        "Protect this circle with honesty and care. Do not keep your place by joining gossip, hiding harm or pushing out someone different. A group that needs a victim to feel united is not practising love. Real belonging does not ask you to leave your values outside.",
        "Look for the person standing at the edge. Learn their name. Invite them without forcing them. Share space and listen to a story unlike your own. The safest communities are built when people who feel secure use that security to welcome, defend and include.",
        "Who near you may be waiting for a simple sign that they are welcome?", "Invite one person into a conversation, meal, game or shared task and listen to them.", R.drawable.icon_friendship),
    personalLetter("disappointed", "When You Feel Disappointed", "Let the Hurt Tell the Truth, Not the Future", "Something mattered and did not happen; feel it without deciding that nothing will work.",
        "My dear one, you expected a person, plan or result to meet you, and it did not. Disappointment can feel smaller than grief to others, but your heart knows the hope that was inside it. You are allowed to name the loss without calling yourself foolish.",
        "Separate what happened from the story pain is adding. ‘This did not work’ is a fact. ‘Nothing will ever work’ is fear speaking too widely. Ask what was outside your control, what can be learned and whether the goal still deserves another path.",
        "Do not punish people for promises they never made, but do speak when an agreement was broken. Adjust the plan with clear eyes. Some hopes should be tried again; others should be released. Wisdom is knowing which one protects your values and future.",
        "What fact is true here, and what painful story are you adding to it?", "Write the fact in one line, then choose whether to retry, adjust, ask or release.", R.drawable.letters_icon_sun),
    personalLetter("embarrassed", "When You Feel Embarrassed", "One Awkward Moment Cannot Define You", "You can repair a mistake, laugh gently and return without hiding yourself.",
        "My dear one, your face may feel hot and your mind may replay the moment again and again. You imagine that everyone is still thinking about it. Most people are carrying their own worries. One awkward word, fall or mistake does not become your name.",
        "If you hurt someone, apologise simply and make it right. If nothing harmful happened, let yourself be human. Do not attack yourself to prove that you understand the mistake. Shame rarely teaches better than calm honesty and a clear plan for next time.",
        "Return to the room, class or conversation when it is safe. Avoiding everything gives the moment more power. You may even smile at your own imperfection without making yourself cruel entertainment. Courage sometimes looks like showing up again with a softer heart.",
        "Does this moment need an apology, a lesson or simply release?", "Do the one repair that is needed, then return to one normal activity you were avoiding.", R.drawable.icon_compassion),
    personalLetter("bored", "When You Feel Bored or Restless", "Look Deeper Before You Run From Quiet", "Boredom may be asking for purpose, rest, challenge or your full attention.",
        "My dear one, nothing seems interesting and your hand keeps reaching for quick noise. Do not judge yourself. Boredom can appear when a task is too easy, too hard, repeated too often or disconnected from meaning. It can also come when your mind is tired.",
        "Pause before filling every empty second. Ask what you need: rest, movement, challenge, company or a clearer reason. If a duty must be done, break it into a short round and give it full attention. If you need rest, choose rest that truly refreshes you.",
        "Quiet can also open a door to curiosity. Notice a bird, draw, repair something, read, help at home or learn how an ordinary object works. You do not need constant excitement to be alive. Attention can reveal wonder inside a simple day.",
        "Is your boredom asking for rest, challenge, meaning or connection?", "Choose one screen-free activity for fifteen minutes that answers the real need.", R.drawable.icon_strategy),
    personalLetter("homesick", "When You Miss Home", "Carry Home in the Values You Live", "Distance can hurt, but love and familiar ways can travel with you.",
        "My dear one, you miss familiar voices, food, rooms, streets or the way life felt before you left. Homesickness can arrive even when this new place is good. Missing home does not mean you made the wrong choice. It means your roots matter to you.",
        "Give those roots a living place. Call someone, cook a familiar meal, keep a small ritual or speak your language with a friend. Then gently learn one thing about where you are now. A new place becomes less strange through repeated, ordinary contact.",
        "Do not compare every new person with someone from home. Let new bonds have their own shape. You can love where you came from and still grow where you stand. Home is not only a place behind you; it also lives in the care and values you carry.",
        "What small part of home would comfort you without closing you to this place?", "Keep one familiar ritual today and introduce yourself to one person or place around you.", R.drawable.icon_relationships)
)

fun krishnaLetter(id: String?): KrishnaLetter = krishnaLetters.firstOrNull { it.id == id } ?: krishnaLetters.first()
