package com.indianservers.krishna4u.feature.teachings

import androidx.annotation.DrawableRes
import com.indianservers.krishna4u.R

data class TeachingUi(
    val id: String,
    val title: String,
    val summary: String,
    val category: String,
    val source: String,
    val question: String,
    val teaching: String,
    val takeaways: List<String>,
    val practice: String,
    @DrawableRes val icon: Int
)

private fun compassion(
    id: String, title: String, summary: String, question: String, teaching: String,
    takeaways: List<String>, practice: String, @DrawableRes icon: Int = R.drawable.icon_compassion
) = TeachingUi(id, title, summary, "Compassion", "Book Chapter 3", question, teaching, takeaways, practice, icon)

private fun gita(
    chapter: Int, title: String, summary: String, question: String, teaching: String,
    takeaways: List<String>, practice: String, @DrawableRes icon: Int = R.drawable.icon_teachings
) = TeachingUi("gita-path-$chapter", title, summary, "Gita Wisdom", "Book Chapter 4 · Gita Chapter $chapter", question, teaching, takeaways, practice, icon)

private fun dharma(
    id: String, title: String, summary: String, question: String, teaching: String,
    takeaways: List<String>, practice: String, @DrawableRes icon: Int = R.drawable.icon_dharma
) = TeachingUi(id, title, summary, "Daily Dharma", "Book Chapter 5", question, teaching, takeaways, practice, icon)

private val bookTeachings = listOf(
    compassion(
        "compassion-cows", "Care for those who depend on you", "Krishna’s bond with the cows of Vrindavan turns care into a daily responsibility.",
        "Who relies on your care even when they cannot ask for it?",
        "Krishna did not treat the cows as objects of usefulness. He knew them, guided them and kept them safe. The episode asks us to widen the circle of family to include animals and every vulnerable life entrusted to us.",
        listOf("Compassion includes animals", "Protection is love made visible", "Responsibility matters even when nobody praises it", "Gentleness and strength can work together"),
        "Offer food, water or safe help to an animal today.", R.drawable.icon_compassion
    ),
    compassion(
        "compassion-fruit-vendor", "A small gift can become abundant", "A fruit vendor’s simple generosity shows that sincerity matters more than the size of a gift.",
        "Would you still give if no one could repay you?",
        "A fruit vendor responded warmly to little Krishna’s innocent offering. The exchange is remembered because the heart behind a gift can be richer than the gift itself. Kindness offered freely creates trust and joy that calculation cannot measure.",
        listOf("Give without keeping score", "A small kindness can carry great meaning", "Sincerity makes an offering valuable", "Generosity creates connection"),
        "Share something useful today without expecting credit.", R.drawable.icon_compassion
    ),
    compassion(
        "compassion-sages", "Let learning make you humble", "Krishna listened to sages with respect and turned knowledge into wise action.",
        "When did you last change your mind after listening carefully?",
        "Although Krishna was revered for wisdom, he still honoured teachers and listened with attention. Knowledge is not a decoration for the ego; it becomes wisdom only when it changes how we speak, choose and serve.",
        listOf("Remain a learner at every age", "Ask sincere questions", "Respect experience without surrendering discernment", "Apply what you understand"),
        "Ask a trusted elder one thoughtful question and listen without interrupting.", R.drawable.icon_teachings
    ),
    compassion(
        "compassion-peacocks", "Live in friendship with nature", "Krishna’s joy among peacocks invites wonder, gratitude and care for the natural world.",
        "Can you enjoy nature without trying to own or disturb it?",
        "The images of Krishna with peacocks and a feather celebrate harmony rather than possession. Nature can teach colour, rhythm, patience and belonging when we slow down enough to notice it.",
        listOf("Wonder is a form of gratitude", "Nature deserves care, not careless use", "Joy can be simple and shared", "Harmony begins with attention"),
        "Spend ten quiet minutes outdoors and leave the place cleaner than you found it.", R.drawable.icon_peacock_feather
    ),
    compassion(
        "compassion-parents", "Remember the people who raised you", "Krishna’s regard for both his birth parents and foster parents teaches gratitude across every form of family.",
        "How can you make care visible at home today?",
        "Krishna’s story holds Devaki and Vasudeva alongside Yashoda and Nanda. It reminds us that family is shaped by sacrifice, protection and presence. Gratitude grows when we notice the unseen work behind our own growth.",
        listOf("Honour both sacrifice and daily care", "Say gratitude while people can hear it", "Family duty includes patience", "Love is strengthened by dependable action"),
        "Thank a parent, guardian or caregiver for one specific thing.", R.drawable.icon_compassion
    ),
    compassion(
        "compassion-insult", "Choose your response after an insult", "A difficult encounter with a proud washerman warns how quickly ego and anger can escalate harm.",
        "When someone insults you, do you protect dignity or feed the conflict?",
        "The episode is best read as a warning about pride, humiliation and uncontrolled reaction. Compassion does not require accepting abuse, but it does ask us to set boundaries without revenge and to prevent one harsh moment from controlling our character.",
        listOf("Pause before anger chooses for you", "Firm boundaries need not become revenge", "Pride can turn a small conflict into lasting harm", "Your response reveals your values"),
        "In your next disagreement, lower your voice and state one clear boundary.", R.drawable.icon_mind
    ),
    compassion(
        "compassion-kubja", "See dignity before appearance", "Krishna’s kindness to Kubja shows how respect can lift someone accustomed to being overlooked.",
        "Do you notice the person others ignore?",
        "Kubja’s encounter with Krishna is remembered as a moment of recognition and transformation. He met her without ridicule and restored a sense of worth. Our attention can either deepen another person’s shame or remind them of their dignity.",
        listOf("Every person deserves respect", "Do not reduce anyone to appearance", "Attention can heal exclusion", "Kindness should restore agency, not create pity"),
        "Include someone who is usually left out of a conversation.", R.drawable.icon_compassion
    ),

    gita(1, "When compassion and duty collide", "Arjuna’s crisis shows that moral discomfort deserves examination, not escape.", "Is your hesitation wisdom—or fear wearing a noble name?", "Before acting, Arjuna allows himself to see the human cost of battle. Krishna’s guidance begins only after that honest pause. Difficult duty needs both compassion and clarity; ignoring either one makes the decision smaller than the problem.", listOf("Name the conflict honestly", "Seek counsel before an irreversible choice", "Compassion must inform duty", "Courage begins after clear seeing"), "Write the two values competing in one decision you face.", R.drawable.icon_dharma),
    gita(2, "Stay steady through change", "Inner steadiness lets you respond wisely when circumstances refuse to stay still.", "What remains yours when praise, comfort or success changes?", "Chapter 2 invites us to distinguish the enduring self from temporary conditions. This is not indifference; it is the stability needed to work sincerely without letting every result decide our worth.", listOf("Feel change without becoming ruled by it", "Measure yourself by values, not applause", "Give full effort without claiming total control", "Equanimity improves judgment"), "Do one important task, then wait ten minutes before checking the result.", R.drawable.icon_courage),
    gita(3, "Serve without needing applause", "Karma Yoga turns ordinary work into service by changing the motive behind it.", "Would you do the right work if your name were never mentioned?", "Selfless action is not passive or careless. It is disciplined contribution without making recognition the price of participation. Work becomes lighter when usefulness matters more than ego.", listOf("Do necessary work promptly", "Let service outrank recognition", "Shared welfare is a worthy result", "Consistency builds character"), "Complete one neglected household or team task quietly.", R.drawable.icon_karma),
    gita(4, "Turn learning into wisdom", "Knowledge becomes purifying when humility, inquiry and action travel together.", "What truth do you understand intellectually but not yet practise?", "Wisdom is more than collecting answers. It asks us to approach good teachers sincerely, question with respect and test insight in the conduct of daily life. Understanding should reduce confusion and ego, not decorate them.", listOf("Learn with humility", "Ask questions that seek truth, not victory", "Test ideas through conduct", "Real knowledge reduces arrogance"), "Choose one principle you know and practise it before bedtime.", R.drawable.icon_teachings),
    gita(5, "Let go of control, not responsibility", "True renunciation releases possessiveness while preserving wholehearted action.", "Can you care deeply without trying to control every outcome?", "Chapter 5 separates withdrawal from inner freedom. You can remain active, responsible and loving while loosening the claim that everything must unfold according to your preference.", listOf("Keep the duty; release the possessiveness", "Peace grows when ego loosens", "Action and inner freedom can coexist", "Accept help from the larger world"), "Finish your part of a shared task without managing everyone else’s part.", R.drawable.icon_karma),
    gita(6, "Train attention patiently", "A wandering mind becomes an ally through repeated, gentle return.", "How do you speak to yourself when concentration breaks?", "Meditation is less about forcing silence than practising return. Balance in sleep, food, work and recreation supports that practice. Harsh self-judgment adds another distraction; patience builds mastery.", listOf("Return attention without self-insult", "Regular practice beats rare intensity", "A balanced routine supports a steady mind", "Notice thoughts without obeying each one"), "Sit for three minutes and return to the breath whenever attention wanders.", R.drawable.icon_mind),
    gita(7, "See the connection behind appearances", "Knowing the source of life changes how we value people, nature and experience.", "Do your beliefs make you more respectful of the world?", "Chapter 7 joins knowledge of the visible world with awareness of its deeper ground. Spiritual insight is credible when it increases wonder, responsibility and a felt connection with life.", listOf("Look for relationship, not isolation", "Let wonder deepen responsibility", "Material knowledge and inner knowledge can cooperate", "Keep inquiry alive"), "Choose one ordinary object and trace how many lives helped bring it to you.", R.drawable.icon_teachings),
    gita(8, "Invest in what endures", "Remembering what is lasting helps us choose priorities before a crisis chooses them for us.", "What are you building that will matter beyond today’s mood?", "Chapter 8 contrasts changing circumstances with the enduring orientation of the heart. Repeated attention shapes us; therefore remembrance, purpose and daily habits matter long before life’s final moments.", listOf("Daily attention becomes character", "Prepare for difficulty through regular practice", "Temporary urgency is not always true importance", "Let purpose guide priorities"), "Remove one low-value distraction from the first hour of tomorrow.", R.drawable.icon_strategy),
    gita(9, "Make devotion sincere", "A simple offering given with love can carry more truth than an impressive display.", "Is your spiritual practice changing how you treat people?", "Chapter 9 presents devotion as accessible, intimate and inclusive. The quality of attention matters more than status or spectacle. Sincere devotion should make ordinary life more generous.", listOf("Offer what you can with a whole heart", "No sincere seeker is excluded", "Devotion belongs in daily conduct", "Gratitude makes simple acts sacred"), "Offer a meal, flower or helpful act with deliberate gratitude.", R.drawable.icon_lotus),
    gita(10, "Recognise the sacred in excellence", "Beauty, courage and wisdom can become reminders of a source larger than the ego.", "When you admire greatness, does it inspire gratitude or comparison?", "Chapter 10 teaches us to see remarkable qualities as windows rather than trophies. Admiration can connect us to the divine when it leads to respect, learning and gratitude instead of envy.", listOf("Let excellence inspire, not diminish you", "Notice greatness in nature and people", "Give credit beyond the individual ego", "Admiration can become a spiritual practice"), "Tell someone exactly what quality in them inspires you.", R.drawable.icon_teachings),
    gita(11, "Meet vastness with humility", "The universal vision places personal worries inside a reality far larger than one viewpoint.", "What changes when you stop treating yourself as the centre of the whole story?", "Arjuna’s vision is awe-inspiring and unsettling. It reminds us that reality exceeds our plans and categories. Humility is not feeling worthless; it is holding our viewpoint as partial while remaining ready to serve.", listOf("Your view is real but incomplete", "Awe can loosen ego", "Humility leaves room for learning", "The larger picture can reorder fear"), "Look at the night sky or a map of Earth and reflect on one worry in that scale.", R.drawable.icon_lotus),
    gita(12, "Make love a daily discipline", "Bhakti is expressed through steadiness, kindness and freedom from hostility.", "What would devotion look like in your behaviour today?", "Chapter 12 brings devotion out of abstraction. Love of the divine becomes visible as patience, goodwill, dependable service and a heart that does not deliberately disturb others.", listOf("Love is a practice, not only a feeling", "Small acts can carry deep devotion", "Kindness is spiritual discipline", "Faith should make others safer around us"), "Do one caring act for a person who cannot reward you.", R.drawable.icon_compassion),
    gita(13, "Know the observer within", "Distinguishing experience from the one who observes it creates room for wiser choice.", "Are you the passing emotion—or the awareness noticing it?", "Chapter 13 compares body and mind to a field and awareness to its knower. When we observe thoughts and sensations clearly, they stop being automatic commands and become information we can respond to.", listOf("Notice before reacting", "The body deserves care without becoming the whole identity", "Emotions are experiences, not permanent definitions", "Awareness creates choice"), "Name one emotion as ‘I notice…’ instead of ‘I am…’.", R.drawable.icon_mind),
    gita(14, "Choose what strengthens clarity", "The three gunas offer a practical lens for noticing what makes us clear, restless or dull.", "Which habits leave your mind brighter, busier or heavier?", "Sattva, rajas and tamas are not labels for condemning people. They help us read patterns in food, media, work and mood so we can deliberately create conditions for clarity.", listOf("Observe patterns without shame", "Use energy without becoming consumed by it", "Rest is different from inertia", "Choose inputs that support clarity"), "After your next activity, note whether you feel clear, agitated or dull.", R.drawable.icon_mind),
    gita(15, "Cut habits at the root", "The inverted tree asks us to examine the hidden attachments feeding visible behaviour.", "What root keeps producing a problem you only trim at the surface?", "Chapter 15’s tree image directs attention from symptoms to sources. Lasting change comes from seeing the belief, craving or fear that feeds a repeated pattern, then reconnecting action to a higher purpose.", listOf("Trace behaviour back to its motive", "Temporary fixes do not remove deep roots", "Purpose helps loosen attachment", "Your choices shape the branches others experience"), "For one recurring habit, write: trigger, hidden need and healthier response.", R.drawable.icon_strategy),
    gita(16, "Build a divine character", "Character grows through repeated choices for truth, courage, compassion and restraint.", "Which quality are your smallest choices strengthening?", "Chapter 16 treats noble and destructive tendencies as directions we reinforce. The useful question is not which label we deserve, but which tendency today’s action will feed.", listOf("Choose truth over convenient deception", "Courage can remain compassionate", "Pride blocks correction", "Character is built in repetitions"), "Choose one quality—patience, truth or generosity—and practise it three times today.", R.drawable.icon_dharma),
    gita(17, "Examine the quality of faith", "Belief is shaped by motive, and motive changes the fruit of practice.", "Does your faith seek truth, applause or permission to avoid thinking?", "Chapter 17 asks us to look beneath the name of a belief to its quality. Faith guided by clarity becomes honest and nourishing; faith driven by display or confusion can distort even disciplined acts.", listOf("Examine motive as well as ritual", "Sincere faith welcomes truth", "Display can empty a good act", "Beliefs should nourish wise conduct"), "Before one good act, privately name your real motive.", R.drawable.icon_lotus),
    gita(18, "Surrender ego, not effort", "The Gita concludes by joining duty, discernment, devotion and freedom from ego.", "Can you commit fully while admitting that life is larger than your plan?", "Chapter 18 does not ask Arjuna to stop thinking. Krishna explains, invites reflection and leaves the choice with him. Mature surrender combines clear judgment, wholehearted effort and trust beyond personal control.", listOf("Reflect before committing", "Act according to your considered duty", "Release ego’s demand to control everything", "Trust can coexist with responsibility"), "Make one decision using facts, values and counsel—then stop rehearsing it.", R.drawable.icon_dharma),

    dharma("dharma-draupadi", "Protect dignity when it is threatened", "Krishna’s support for Draupadi calls us to stand beside people facing humiliation or injustice.", "Will you stay silent because the wrong is not aimed at you?", "Draupadi’s ordeal exposes the failure of spectators as much as the cruelty of offenders. Dharma asks us to protect dignity, seek help and refuse to normalise public humiliation.", listOf("Do not make silence an ally of injustice", "Support the person being targeted", "Ask responsible adults or authorities for help", "Courage can begin with one clear objection"), "Safely interrupt one act of exclusion or report it to someone responsible.", R.drawable.icon_courage),
    dharma("dharma-charioteer", "Guide without taking away agency", "As Arjuna’s charioteer, Krishna combines humble service with clear counsel.", "Can you help someone without controlling their decision?", "Krishna listens, questions, teaches and steadies Arjuna, yet the final choice remains Arjuna’s. Good mentors illuminate the road and strengthen the traveller.", listOf("Listen before advising", "Serve without needing the highest seat", "Explain reasons, not only commands", "Leave the learner stronger"), "Ask a friend whether they want listening, advice or practical help.", R.drawable.icon_leadership),
    dharma("dharma-ugrasena", "Restore rightful leadership", "Krishna’s support for Ugrasena places justice above personal power.", "Would you return authority when you could keep it for yourself?", "After tyranny was removed, Krishna did not treat victory as a licence for self-promotion. The lesson is that leadership exists to restore order, protect people and place responsibility where it can be exercised justly.", listOf("Power is a trust, not a prize", "Justice matters more than personal glory", "Restore institutions after removing harm", "A leader protects the common good"), "Give ownership of a task back to the person best placed to lead it.", R.drawable.icon_leadership),
    dharma("dharma-bhishma", "Test promises against the greater good", "Bhishma’s vow reveals how a noble promise can create painful consequences when context changes.", "Should every promise be kept in exactly the same form, whatever the harm?", "Commitment matters, but dharma also asks what a commitment now protects or damages. Integrity needs reflection, humility and the courage to seek wise counsel when duties collide.", listOf("Keep promises thoughtfully", "Do not use a vow to avoid moral responsibility", "Consider foreseeable harm", "Seek counsel when duties conflict"), "Review one commitment and clarify the value it was meant to serve.", R.drawable.icon_dharma),
    dharma("dharma-narakasura", "Use strength to protect the vulnerable", "The Narakasura episode frames courage as resistance to oppression and restoration of dignity.", "What is strength for if it never protects anyone?", "Dharma does not admire power for its own sake. It asks that strength be disciplined, proportionate and directed toward freeing people from fear rather than creating more fear.", listOf("Strength carries responsibility", "Protect rather than dominate", "Restore dignity after harm", "Intervene safely and proportionately"), "Use your influence to make one vulnerable person safer or better heard.", R.drawable.icon_courage),
    dharma("dharma-syamantaka", "Let evidence answer suspicion", "The Syamantaka jewel dispute teaches calm investigation when reputation is attacked.", "When accused unfairly, will you spread anger or search for truth?", "Krishna responds to suspicion by pursuing facts and resolving the underlying conflict. A clear name is best protected through evidence, patience and transparent action rather than louder accusation.", listOf("Investigate before blaming", "Keep records when facts matter", "Do not let gossip become evidence", "Resolve the cause, not only the argument"), "In one disagreement, separate what you know from what you assume.", R.drawable.icon_strategy),
    dharma("dharma-beliefs", "Share conviction without contempt", "Krishna’s teachings challenge inherited habits while respecting the listener’s freedom to understand.", "Can you explain what you believe without insulting someone else?", "Confidence does not need mockery. A strong idea can be offered with reasons, openness and respect. The goal is not to win a performance but to help people see responsibility and meaning more clearly.", listOf("Explain rather than attack", "Confidence welcomes questions", "Respect people while challenging ideas", "Let conduct support your words"), "State one belief using ‘I value… because…’ rather than judging another person.", R.drawable.icon_teachings),
    dharma("dharma-strategy", "Plan before pressure arrives", "Krishna’s role in the Mahabharata shows that righteous intention still needs foresight.", "Is a good heart enough when a difficult situation demands preparation?", "Strategy can serve dharma when it anticipates consequences, protects people and chooses timing wisely. Planning is not manipulation when it remains accountable to truth and the common good.", listOf("Think beyond the first consequence", "Prepare alternatives", "Keep means aligned with values", "Calm planning reduces panic"), "For one goal, write the next step, one risk and one backup plan.", R.drawable.icon_strategy),
    dharma("dharma-uddhava", "Choose friends who help you grow", "Krishna and Uddhava represent friendship enriched by trust, inquiry and spiritual conversation.", "Do your closest friendships make honesty easier?", "A strong friend does more than entertain. Friendship can hold questions, correction, encouragement and shared growth without becoming competitive or controlling.", listOf("Make room for meaningful conversation", "Tell the truth kindly", "Celebrate a friend’s growth", "Receive correction without defensiveness"), "Ask a friend one question about the person they hope to become.", R.drawable.icon_friendship),
    dharma("dharma-peacocks", "Protect what gives life beauty", "Krishna’s association with peacocks turns delight in nature into a duty of care.", "What beauty around you depends on someone choosing not to damage it?", "Love of nature is incomplete if it ends at admiration. Wonder should change how we use water, handle waste and share space with other living beings.", listOf("Enjoy nature respectfully", "Beauty creates responsibility", "Small habits affect shared habitats", "Gratitude should reduce waste"), "Carry reusable water and remove one piece of litter safely.", R.drawable.icon_peacock_feather),
    dharma("dharma-protect-arjuna", "Be calm support in a crisis", "Krishna’s protection of Arjuna models alert, steady help when pressure is high.", "Can others borrow calm from you when things go wrong?", "Useful support is neither panic nor empty reassurance. It notices danger, communicates clearly and helps the other person take the next workable step.", listOf("Stay present under pressure", "Give clear, practical help", "Do not make another person’s crisis about yourself", "Preparation strengthens courage"), "Learn one emergency contact or safety step relevant to your home or school.", R.drawable.icon_courage),
    dharma("dharma-shishupala", "Let patience have wise boundaries", "Krishna’s long patience with Shishupala teaches that forgiveness and accountability must coexist.", "When does repeated tolerance begin to protect harmful behaviour?", "Forgiveness can release hatred, but it does not require endless access or the absence of consequences. Responsible boundaries protect both dignity and the wider community.", listOf("Forgiveness is not permission", "State boundaries before resentment grows", "Use fair consequences", "Seek safe help for repeated harm"), "Write one boundary as: ‘If this happens, I will…’.", R.drawable.icon_dharma),
    dharma("dharma-pandavas", "Stay loyal through difficulty", "Krishna’s friendship with the Pandavas is most visible when their fortunes are lowest.", "Do you disappear when a friend’s life becomes inconvenient?", "Loyalty is not blind agreement. It is dependable presence, honest counsel and practical support during hardship, while still keeping both friends aligned with dharma.", listOf("Show up during setbacks", "Loyalty includes honest correction", "Protect trust", "Do not exploit a friend’s vulnerability"), "Check in with someone going through a difficult week.", R.drawable.icon_friendship),
    dharma("dharma-cows", "Make care a routine", "Krishna’s life among cows teaches attentive responsibility toward animals and dependants.", "Is your kindness reliable, or only present when it feels convenient?", "Daily care is built from feeding, noticing, cleaning, guiding and protecting. Affection becomes trustworthy when it is organised into consistent action.", listOf("Routine is part of compassion", "Notice needs before they become emergencies", "Treat animals gently", "Dependability creates safety"), "Take responsibility for one recurring care task this week.", R.drawable.icon_compassion),
    dharma("dharma-humble-service", "No honest task is beneath a leader", "Krishna’s service at the Rajasuya gathering places humility at the heart of honour.", "Would you still help if the task looked too ordinary for your status?", "Leadership becomes credible when it shares necessary work. Humble service is not self-erasure; it is freedom from the need to prove importance through distance from ordinary duties.", listOf("Status does not cancel service", "Notice unglamorous work", "Share the load", "Humility earns trust"), "Choose the least celebrated useful task in your group and do it well.", R.drawable.icon_leadership),
    dharma("dharma-coronation", "Let leadership serve everyone", "Krishna’s counsel around Yudhishthira’s rule centres fairness, compassion and public welfare.", "Who benefits from the decisions you lead?", "Good leadership listens beyond its supporters, protects those with less power and accepts responsibility for consequences. Success is measured by the wellbeing and justice a leader helps create.", listOf("Listen before deciding", "Protect minority voices", "Use consistent standards", "Accept responsibility for outcomes"), "Before a group decision, invite input from the quietest member.", R.drawable.icon_leadership),
    dharma("dharma-timely-protection", "Act before danger becomes disaster", "Stories of Krishna protecting the Pandavas stress vigilance and timely intervention.", "Do you wait for certainty when warning signs already demand a safe response?", "Care pays attention. When risk is credible, a responsible person warns others, seeks qualified help and takes proportionate preventive action rather than waiting for harm to prove the warning correct.", listOf("Notice warning signs", "Warn without creating panic", "Seek capable help early", "Prevention is an act of care"), "Fix or report one small safety risk you have been ignoring.", R.drawable.icon_strategy),
    dharma("dharma-truth-dilemma", "Do not make truth a clever loophole", "The Ashwatthama episode exposes the moral cost of strategic ambiguity during crisis.", "Can words be technically true and still deliberately mislead?", "The Mahabharata does not make every wartime choice comfortable. This episode should sharpen conscience: clever wording can protect an aim while wounding trust. In ordinary life, choose truthful, clear and compassionate communication whenever safety permits.", listOf("Technical truth can still deceive", "Urgency does not erase moral cost", "Consider what your listener will reasonably understand", "Repair trust when words cause harm"), "Correct one misleading impression you have allowed to continue.", R.drawable.icon_dharma)
)

val teachingLibrary = bookTeachings + krishnaGuidanceTeachings

fun teachingById(id: String?): TeachingUi = teachingLibrary.firstOrNull { it.id == id } ?: teachingLibrary.first()
